<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit171c10beadcf6d76a423d392b15c5f35
{
    public static $prefixLengthsPsr4 = array (
        'L' => 
        array (
            'Loquat\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Loquat\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit171c10beadcf6d76a423d392b15c5f35::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit171c10beadcf6d76a423d392b15c5f35::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
